blank_issues_enabled: false
contact_links:
  - name: Package issue
    url: https://github.com/orchidsoftware/platform
    about: Package-related bug reports
  - name: Discussions
    url: https://github.com/orchidsoftware/platform/discussions/new
    about: 'If you want to start a discussion or want to ask a question, click:'
